### ISSUE TITLE
Light is deprecated, modify ModernFormsLight to extend LightEntity

### ISSUE THREAD

**Issue by mikeyroth** [jimpastos/ha-modernforms#1]
Getting this in the log   Is there a fix?

**Comment by jimpastos** [comment]
Ah, what version of HA? I can probably look into when Im back at home. Away for a few days

**Comment by jimpastos** [comment]
Also does this break the integration or is it just a warning?

**Comment by mikeyroth** [comment]
Just a warning.  Home assistant 0.110.3  HASSOS 4.8

**Comment by jimpastos** [comment]
Fixed with latest push
