### ISSUE TITLE
investigate aiohttp in place of httpx

### ISSUE THREAD

**Issue by faceprint** [jimpastos/ha-modernforms#18]
Investigate using aiohttp in place of httpx due to some quirks with read timeouts.

**Comment by icemarkom** [comment]
FYI - I think `aiohttp` works fine. I have no objections to replace `httpx` with it.

**Comment by icemarkom** [comment]
I've been running this for a few weeks now, and it's rock solid stable (fans still crash, but I do not believe it's related). Any chance you can send a PR, so we can move on? :-)

**Comment by faceprint** [comment]
I filed https://github.com/jimpastos/ha-modernforms/pull/19 with everything pushed to my fork.  It's got multiple changes, I don't hve time to separate them out, but if you or anyone wants to just merge pieces, I have no objection.
